### ISSUE TITLE
send RC

### ISSUE THREAD

**Issue by alduxvm** [renes/multiwiiDataLogger#1]
Hi!

Very nice code all over... quick question, how could you send RC commands??

should the data be packed like this? 

data = [ 1000, 1000, 1000, 1000, 2000, 1000, 1000, 1000 ];
p.send_msp( MSP_SET_RAW_RC  ,data, 0);

but there is no checksum function right??

cheers!

**Comment by renes** [comment]
The check sum is calculated in the function - you don't have to care about it

 Best regards rene
